### PR TITLE
Render custom emojis

### PR DESCRIPTION
**Pull request by dawran6**
This is still WIP.

Problem: #75 

Solution:

- [x] Get all custom emojis from slack api: `emoji.list`
- [x] Add Datomic schema for emojis
- [x] Import emojis to Datomic
- [x] Recursively resolve emoji alias/shortcode to its an url or an unicode
- [x] Render `img` tag for urls; plain string for unicodes
- [x] Add style for inline emoji `img` tag
- [x] Add tests
- [x] Pass emoji map to the render function

### CODE REVIEW

**Comment by dawran6** [comment]
Feel free to give me your feedback.

**Comment by plexus** [comment]
Looks great!

**Comment by dawran6** [comment]
Thanks! To be clear, this PR so far hasn't render the custom emoji `img` tags yet. It still needs to pass down the emoji map to the render function. I assume it'll be somewhat like the function `clojurians-log.slack-messages/replace-ids-names`.

**Comment by dawran6** [comment]
I haven't figured out how to center the emoji yet, but I think this can come later.

image

**Comment by dawran6** [comment]
Would you take a look again, @plexus? I think this PR is ready.
In order to render the custom emojis, one needs to import the emojis first. See `clojurians-log-app/load-slack-data!` where it calls:

```clojure
(slack/import-emojis! (conn))
```

I'm not sure how this is done in the production but I want to point it out.

**Comment by plexus** [comment]
Nice! Sorry for the delay, I was caught up with ClojuTRE :)

I can run the import manually. If it should happen regularly we should bake that in, similar to the indexer component.

**Comment by plexus** [comment]
Ah I see, `load-slack-data` gets called each time we import new messages, which is once every fifteen minutes right now, so that should be good.

**Comment by plexus** [comment]
Nice: https://clojurians-log.clojureverse.org/announcements/2019-09-20

**Comment by plexus** [comment]
Note that @rgm is also a maintainer, so feel free to ping him as well to get things merged. And if no one responds within a day or two you are more than welcome to merge your own stuff.

**Comment by dawran6** [comment]
Sweet! Thank you :)

**Pull request merged**
