### PR TITLE
About link on top of page

### PR DESCRIPTION
**Pull request by kloimhardt**
Adds an About section describing the purpose of the project and inviting to contribute.

- [X] add about link on main page
- [X] read text from markdown file
- [X] display text on About page

This PR is feature complete and ready for review

### CODE REVIEW

**Comment by plexus** [comment]
Looks good! Is this ready? @kloimhardt might be a good habit to use the PR description to say a few words about what you did and what the status is. Especially if it's still work-in-progress then you should mention that.

Something we should think about: this software is also used by some other slack communities (http://itrevbookclub-archive.itrevolution.com/ and http://devopsenterprise-archive.itrevolution.com/), so some way to make the about bit configurable would be useful. Maybe loading it from a Markdown file on the classpath? that way you can put a file with different contents earlier on the classpath to override the default.

**Comment by kloimhardt** [comment]
Thank you for the guidance. I realise that 
1) I definitely need to more verbose:
will write more in commits and in PR descriptions.
2) I should not create a PR too early:
I thought the PR is finished when pushing the first time, and then I saw the possibility of improvement. (Made the improvement and was (maybe wrongly) thinking it to be a good idea to just wait for your response).

I have two small pull requests in the pipeline (one for the sitemap and one with some styles migrated from legacy.css to style.css). I'll keep them local until the PR process is smoothed by working on this one "about" PR.

Concerning this PR: will add the "Markdown on class path" feature in this PR and try to clearly communicate the status in the commit message (and not making too many commits). However, I will not concern myself with better css styling in this PR, as I want to wait until the above mentioned to-be-published extra CSS PR is merged into master.

**Comment by plexus** [comment]
It's fine to push and create a PR early on. That way people see what you're doing (and for instance won't work on the same thing), and you can get early feedback or discuss the approach. Just mention in the description if it's still WIP. 

Something you can also use this for is to put a checklist of what you still want to do in the description. That way it's immediately clear what the status is.

For instance

----

- [ ] finish up styling
- [ ] update README

**Comment by plexus** [comment]
Good job! Thanks!

**Pull request merged**
