### PR TITLE
docs: add testing instructions

### PR DESCRIPTION
**Pull request by oxalorg**
Problem: How to run tests were not mentioned in the README

Solution: Added instructions for testing via the `bin/kaocha` script and via the REPL.

### CODE REVIEW

**Comment by plexus** [comment]
Thanks!

singin-dancin

I'm going to rephrase that REPL example a bit, I don't want to encourage bad habits with `use`.

**Comment by plexus** [comment]
I see now that we do the same thing in the Kaocha docs :facepalm: ... so maybe I should fix that first. Will leave it here as is for now.

**Comment by oxalorg** [comment]
Ah yes, I just took the same way it was written in the Koacha docs 🙈 

Typically we should prefer `require` because it is more explicit and to avoid the possibility of overriding existing names right?

Should I make the change in both the repos to this example instead:

```
(require '[kaocha.repl :as k])
(k/run 'clojurians-log.views-test)
```

**Comment by plexus** [comment]
Yes, that would be great! thanks!

**Pull request merged**
