### PR TITLE
Render parsed messages as hiccup

### PR DESCRIPTION
**Pull request by jxa**
Relates to #1 /cc @camachom 

This is a first pass at rendering rich slack messages. Certain things are still missing, such as URL parsing and channel name handling. 

datomic 2018-02-08 clojurians slack log 2018-03-04 13-24-40

### CODE REVIEW

**Comment by jxa** [comment]
re-frame 2018-02-06 clojurians slack log 2018-03-04 20-52-19

**Comment by plexus** [comment]
hi @jxa, this looks good. Nice to see the messages render properly.

One thing I should have mentioned before, please don't merge your own PR's, instead get someone to review and merge them. This is a pretty common policy on projects, so at least one other person has checked off on the changes. Thanks!

**Comment by jxa** [comment]
@plexus sorry about that! I mis-read your intent when you sent the invite to collaborate. I'll make sure to get reviews in the future

**Comment by plexus** [comment]
No worries, I can't expect you to read my mind. I'll try to get some contributing guidelines up. I decided to grant commit bit pretty quickly on this project to encourage people to keep contributing. At the same time we're all here to learn and improve, and this is meant to be an examplar project for the clojure community, so I hope we can foster a good culture of reviews and positive feedback.

**Pull request merged**
