### PR TITLE
Fixed local deployment instructions

### PR DESCRIPTION
**Pull request by pradeepbishnoi**

### CODE REVIEW

**Comment by pradeepbishnoi** [comment]
@plexus for your review.

**Comment by oxalorg** [comment]
Thanks for updating the README. But looks like this PR includes the commits made in #129 (I've requested some changes on that PR)

**Comment by pradeepbishnoi** [comment]
Seems to have happened because of the changes merged into my main branch and then PR raised via main. Will resolve them sooner.

**Comment by oxalorg** [comment]
Merged :taco: :tada: 

ty4

**Comment by pradeepbishnoi** [comment]
we still need to work on having the test data loading to preview new feature like emoji etc.

**Comment by plexus** [comment]
Thanks Pradeep! Good stuff!

**Pull request merged**
