### PR TITLE
Clean legacy css

### PR DESCRIPTION
**Pull request by kloimhardt**
The goal of this PR is to get rid of legacy.css

- [X] moved four css-styles from legacy.css to styles.clj
- [X] hand checked that this seems sufficient to remove legacy.css 
- [x] check by some more advanced method, whether all necessary styles are now indeed moved to styles.clj
- [x] remove the file legacy.css from repository

### CODE REVIEW

**Comment by kloimhardt** [comment]
Before actually removing legacy.css I'd like to make sure that no part of the site is accessing it. I hand checked the according hiccup-html, but I do not feel confident here. **@plexus**: Is there another way to check this? Maybe program some error message mechanism indicating if a style is missing before removing legacy.css from the codebase?

**Comment by plexus** [comment]
I wouldn't worry about it too much. We basically only have three kinds of pages: the top level index, the index per channel, and the page with messages. If they all still look good in your browser then I think that's all that matters.

**Comment by kloimhardt** [comment]
PR is ready to merge into master

**Comment by plexus** [comment]
Good stuff! Thanks!

excellent

**Pull request merged**
